# Generated by Django 5.1.4 on 2025-02-01 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Docente',
                'verbose_name_plural': 'Categorías de Docentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutional_email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Institucional')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Personal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('profession', models.CharField(max_length=200, verbose_name='Profesión')),
                ('academic_degree', models.CharField(max_length=200, verbose_name='Grado Académico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Adjunto/Regular/etc.', on_delete=django.db.models.deletion.PROTECT, to='MEECETeacherManager.teachercategory', verbose_name='Categoría')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='MEECETeacherManager.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Perfil de Docente',
                'verbose_name_plural': 'Perfiles de Docentes',
            },
        ),
    ]
