# Generated by Django 5.1.4 on 2025-02-01 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0002_teachercategory_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Asignatura')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Asignatura')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10, verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Término')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Término')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='MEECETeacherManager.course', verbose_name='Asignatura')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='MEECETeacherManager.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Carga Horaria',
                'verbose_name_plural': 'Cargas Horarias',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
