# Generated by Django 5.1.4 on 2025-02-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0004_globalteacherlink_teacherpersonallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo Institucional'),
        ),
    ]
