# Generated by Django 5.1.4 on 2025-02-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0005_alter_teacherprofile_institutional_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=200, verbose_name='Grado Académico'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profesión'),
        ),
    ]
