# Generated by Django 5.1.4 on 2025-02-02 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0007_alter_teacherprofile_institutional_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalteacherlink',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='globalteacherlink',
            name='url_pattern',
        ),
        migrations.CreateModel(
            name='TeacherGlobalLinkURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_urls', to='MEECETeacherManager.globalteacherlink')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_link_urls', to='MEECETeacherManager.teacher')),
            ],
            options={
                'verbose_name': 'URL de Link Global',
                'verbose_name_plural': 'URLs de Links Globales',
                'unique_together': {('teacher', 'global_link')},
            },
        ),
    ]
