# Generated by Django 5.1.4 on 2025-02-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0008_remove_globalteacherlink_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschedule',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='¿El docente aceptó la carga horaria?'),
        ),
    ]
