# Generated by Django 5.1.4 on 2025-02-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0009_teacherschedule_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Tarea')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarea de Cumplimiento',
                'verbose_name_plural': 'Tareas de Cumplimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Completado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_statuses', to='MEECETeacherManager.teacher')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='MEECETeacherManager.compliancetask')),
            ],
            options={
                'verbose_name': 'Estado de Cumplimiento',
                'verbose_name_plural': 'Estados de Cumplimiento',
                'unique_together': {('task', 'teacher')},
            },
        ),
    ]
