# Generated by Django 5.1.4 on 2025-02-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0010_compliancetask_compliancestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='validity_period',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='Periodo de vigencia'),
        ),
    ]
