# Generated by Django 5.1.4 on 2025-02-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0011_course_validity_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='validity_period',
        ),
    ]
