# Generated by Django 5.1.4 on 2025-02-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0012_remove_course_validity_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modality',
            field=models.CharField(choices=[('SYNC', 'Online Sincrónica'), ('ASYNC', 'Online Asincrónica'), ('PRES', 'Presencial')], default='PRES', max_length=5, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='course',
            name='vacancies',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Vacantes'),
        ),
    ]
