# Generated by Django 5.1.4 on 2025-02-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0013_course_modality_course_vacancies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='course',
            name='vacancies',
        ),
    ]
