# Generated by Django 5.1.4 on 2025-02-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0014_remove_course_modality_remove_course_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschedule',
            name='modality',
            field=models.CharField(choices=[('SYNC', 'Online Sincrónica'), ('ASYNC', 'Online Asincrónica'), ('PRES', 'Presencial')], default='PRES', max_length=5, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='vacancies',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Vacantes'),
        ),
    ]
