# Generated by Django 5.1.4 on 2025-02-04 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0016_teacherschedule_intake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('faculty', models.CharField(max_length=200, verbose_name='Facultad')),
                ('school', models.CharField(max_length=200, verbose_name='Escuela')),
                ('campus', models.CharField(max_length=200, verbose_name='Sede/Campus')),
                ('period', models.CharField(max_length=50, verbose_name='Período')),
                ('program_code', models.CharField(max_length=50, verbose_name='Código de Programa')),
                ('program_name', models.CharField(max_length=255, verbose_name='Nombre de Programa')),
                ('program_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'MPA',
                'verbose_name_plural': 'MPAs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MPASheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=100, verbose_name='Nombre de la hoja')),
                ('intake', models.CharField(max_length=100, verbose_name='INTAKE')),
                ('mpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='MEECETeacherManager.mpa', verbose_name='MPA')),
            ],
            options={
                'verbose_name': 'Hoja de MPA',
                'verbose_name_plural': 'Hojas de MPA',
                'ordering': ['sheet_name'],
                'unique_together': {('mpa', 'sheet_name')},
            },
        ),
        migrations.CreateModel(
            name='MPASchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50, verbose_name='Período')),
                ('nrc', models.CharField(max_length=20, verbose_name='NRC')),
                ('course_code', models.CharField(max_length=20, verbose_name='Código Asignatura')),
                ('section', models.CharField(max_length=10, verbose_name='Sección')),
                ('course_name', models.CharField(max_length=255, verbose_name='Nombre Asignatura')),
                ('activity', models.CharField(max_length=50, verbose_name='Actividad')),
                ('modality', models.CharField(max_length=100, verbose_name='Modalidad')),
                ('vacancies', models.IntegerField(verbose_name='Cantidad de Vacantes')),
                ('day', models.CharField(max_length=20, verbose_name='Día')),
                ('schedule', models.CharField(max_length=50, verbose_name='Horario (módulo)')),
                ('duration', models.CharField(max_length=20, verbose_name='Duración (semanas)')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Término')),
                ('teacher_rut', models.CharField(max_length=20, verbose_name='RUT')),
                ('teacher_name', models.CharField(max_length=200, verbose_name='Nombre Profesor')),
                ('building', models.CharField(max_length=100, verbose_name='Edificio')),
                ('classroom', models.CharField(max_length=100, verbose_name='Sala')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Hora')),
                ('catalog_hours', models.IntegerField(blank=True, null=True, verbose_name='Horas Catálogo')),
                ('responsibility_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Responsabilidad')),
                ('payable_hours', models.IntegerField(blank=True, null=True, verbose_name='Horas a Pagar')),
                ('installments', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Cuotas')),
                ('installment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Cuota')),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total a Pagar')),
                ('folio', models.CharField(blank=True, max_length=50, null=True, verbose_name='FOLIO')),
                ('budget', models.CharField(blank=True, max_length=50, null=True, verbose_name='PPTO')),
                ('minimum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mínimo')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='MEECETeacherManager.mpasheet', verbose_name='Hoja')),
            ],
            options={
                'verbose_name': 'Horario de MPA',
                'verbose_name_plural': 'Horarios de MPA',
                'ordering': ['period', 'course_code', 'section'],
            },
        ),
    ]
