# Generated by Django 5.1.4 on 2025-02-06 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0017_mpa_mpasheet_mpaschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('event_type', models.CharField(choices=[('GENERAL', 'Evento General'), ('COURSE_START', 'Inicio de Curso'), ('COURSE_END', 'Término de Curso'), ('MILESTONE', 'Hito'), ('ALERT', 'Alerta')], default='GENERAL', max_length=20, verbose_name='Tipo de Evento')),
                ('event_date', models.DateTimeField(verbose_name='Fecha del Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('highlight', models.BooleanField(default=False, verbose_name='Destacado')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícono')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('mpa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='MEECETeacherManager.mpa')),
                ('mpa_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='MEECETeacherManager.mpaschedule')),
            ],
            options={
                'verbose_name': 'Evento de Timeline',
                'verbose_name_plural': 'Eventos de Timeline',
                'ordering': ['event_date'],
            },
        ),
    ]
