# Generated by Django 5.1.4 on 2025-02-08 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEECETeacherManager', '0019_timelineevent_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='mpa_schedule',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('GENERAL', 'Evento General'), ('COURSE_START', 'Inicio de Curso'), ('COURSE_END', 'Término de Curso'), ('MILESTONE', 'Hito'), ('ALERT', 'Alerta')], default='GENERAL', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='icon',
            field=models.CharField(blank=True, choices=[('fa-star', 'Estrella'), ('fa-flag', 'Bandera'), ('fa-exclamation-circle', 'Alerta'), ('fa-check-circle', 'Check'), ('fa-info-circle', 'Info'), ('fa-calendar', 'Calendario'), ('fa-clock', 'Reloj')], max_length=50, verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='mpa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEECETeacherManager.mpa'),
        ),
    ]
