# Generated by Django 5.1.4 on 2024-12-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='work_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workmanager.workzone'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'work_zone')},
        ),
    ]
