# Generated by Django 5.1.4 on 2024-12-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmanager', '0002_tag_work_zone_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='work_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workmanager.workzone'),
        ),
    ]
