# Generated by Django 5.1.4 on 2024-12-09 01:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workmanager', '0003_alter_tag_work_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
