# Generated by Django 5.1.4 on 2024-12-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmanager', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='workzone',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workzone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
