# Generated by Django 5.1.4 on 2025-02-01 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmanager', '0006_workzone_color_workzone_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkZoneApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-tool', help_text='Nombre del ícono de FontAwesome', max_length=50)),
                ('url_name', models.CharField(help_text='Nombre de la URL de la aplicación', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='workmanager.workzone')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
